version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.16.3
  environment:
    REPO: hook-webpack-plugin
    NPM_VERSION: 6.11.3
    COVERALLS_SERVICE_NAME: circleci
  working_directory: ~/hook-webpack-plugin

restore_node_modules: &restore_node_modules
  restore_cache:
    name: 'Restore node_modules cache'
    keys:
      - node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - node_modules-{{ .Branch }}-
      - node_modules-

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build
          filters: # Required by publish.
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: 'Install dependencies'
          command: |
            if [ ! -d node_modules ]; then
              sudo npm install -g npm@${NPM_VERSION}
              npm ci
            fi
      - save_cache:
          name: 'Save node_modules cache'
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: 'Test'
          command: npm test
  publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: 'Publish to NPM'
          command: |
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
            npm publish
