version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.16.3
  environment:
    REPO: hook-webpack-plugin
    NPM_VERSION: 6.11.3
    COVERALLS_SERVICE_NAME: circleci
  working_directory: ~/hook-webpack-plugin

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9].+/
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: 'Restore node_modules cache'
          keys:
            - node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node_modules-{{ .Branch }}-
            - node_modules-
      - run:
          name: 'Install dependencies'
          command: |
            if [ ! -d node_modules ]; then
              sudo npm install -g npm@${NPM_VERSION}
              npm ci
            fi
      - run:
          name: 'Test'
          command: npm test
      - save_cache:
          name: 'Save node_modules cache'
          key: node_modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 'Publish to NPM'
          command: |
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
            npm publish
